# Generated by Django 3.0.3 on 2020-03-14 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='arc',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='cont',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 10, 4, 53, 266095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='hold',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='hv',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='knr',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='trip',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=0),
        ),
    ]
