# Generated by Django 3.0.3 on 2020-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200314_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='cont',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=2),
        ),
        migrations.AlterField(
            model_name='data',
            name='dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='hold',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=2),
        ),
        migrations.AlterField(
            model_name='data',
            name='hv',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=2),
        ),
        migrations.AlterField(
            model_name='data',
            name='knr',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=2),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'OK')], default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='trip',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass'), (2, 'Bypass')], default=2),
        ),
    ]
