# Generated by Django 3.0.3 on 2020-08-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mailstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine',
            field=models.PositiveIntegerField(choices=[(1, 'In'), (2, 'Out')], verbose_name='Machne Number'),
        ),
    ]
