# Generated by Django 3.0.3 on 2020-08-13 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200813_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('to', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
            ],
        ),
    ]
